from numpy import *
x = arange(0,10,0.01)
y = sin(x)
z=cos(x)
p=cosh(x)
q=sinh(x)
print('sine values of x from zero to ten wiht incr. 0.01')
print(y)
print('cos values of x from zero to ten with incr. 0.01')
print(z)
print('hyperbolic cos fn')
print(p)
print('hyperboic sin fn')
print(q)